version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/src/main/resources/application.properties

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: mockinterview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

